version: '3.8'

services:

  db:
    image: "postgres"
    container_name: db
    environment:
      TZ: "Europe/Kiev"
      PGTZ: "Europe/Kiev"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "rent-cars"
    ports:
      - "5432:5432"
    volumes:
     - postgres-data:/var/lib/postgresql/data

  test_db:
    image: "postgres"
    container_name: test_db
    environment:
      TZ: "Europe/Kiev"
      PGTZ: "Europe/Kiev"
      POSTGRES_USER: "test_postgres"
      POSTGRES_PASSWORD: "test_postgres"
      POSTGRES_DB: "rent-cars-test"
    ports:
      - "5433:5432"


volumes:
  postgres-data:
