"""create models

Revision ID: 02acfe38afe4
Revises: 
Create Date: 2023-08-16 20:29:21.474919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02acfe38afe4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('car_description', sa.String(length=32), nullable=False),
                    sa.Column('car_number', sa.String(length=16), nullable=False),
                    sa.Column('transmission', sa.String(length=16), nullable=False),
                    sa.Column('engine', sa.String(length=16), nullable=False),
                    sa.Column('year', sa.Integer(), nullable=False),
                    sa.Column('status', postgresql.ENUM('active', 'broken', 'repairing', 'busy', name='status_car'),
                              nullable=False),
                    sa.Column('image', sa.String(length=64), nullable=True),
                    sa.Column('rental_cost', sa.Integer(), nullable=False),
                    sa.Column('car_station_id', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_cars_car_number'), 'cars', ['car_number'], unique=False)
    op.create_table('reviews',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('comment', sa.Text(), nullable=False),
                    sa.Column('stars', sa.Integer(), nullable=False),
                    sa.Column('car_id', sa.Integer(), nullable=False),
                    sa.Column('parent_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['parent_id'], ['reviews.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_index(op.f('ix_cars_car_number'), table_name='cars')
    op.drop_table('cars')
    op.execute('DROP TYPE IF EXISTS status_car')
    # ### end Alembic commands ###
