services:

  dynamodb:
    image: amazon/dynamodb-local:1.20.0
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    user: root
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"


volumes:
  dynamodb-data:
