name: Run linter and tests for car service

on:
  pull_request:
    types: [opened, synchronize]


jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cars_service
        
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: test_postgres
          POSTGRES_PASSWORD: test_postgres
          POSTGRES_DB: rent-cars-test

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
          cache: 'poetry'

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --no-root
        
      - name: Linter
        run: |
          poetry run python -m flake8
       
      - name: Test with pytest
        run: |
          poetry run pytest ./tests
