name: Run linter websocket service

on:
  pull_request:
    types: [opened, synchronize]


jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: websocket_service 

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
          cache: 'poetry'

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --no-root
        
      - name: Linter
        run: |
          poetry run python -m flake8
          
